export { default as Inicio } from './Home/Inicio'
export { default as Suporte } from './Home/Suporte'
export { default as Receitas } from './Receita/Receitas'
export { default as Iscadefrango } from './Receita/Iscadefrango'
export { default as Treinos } from './Treino/Treinos'
export { default as Resistencia } from './Treino/Resistencia'
export { default as Usuario } from './Usuario'
export { default as Cadastrar } from './Cadastrar'